### ISSUE TITLE
DOM Body Contrast

### ISSUE THREAD

**Issue by AustinPaquette** [Forcir/design#22]
Add a body-contrast option (class).

```SCSS
.body {
    &.contrast {
        background-color: #eceeef;
    }
}
```

Would be useful for easily creating off-white pages
